buildscript {
    repositories {
        maven { url "https://repo.grails.org/grails/core" }
        mavenCentral()
    }
    dependencies { // Not Published to Gradle Plugin Portal
        classpath "org.grails:grails-gradle-plugin:6.2.4"
        classpath "org.grails.plugins:hibernate5:8.1.0"
        classpath "org.grails.plugins:views-gradle:3.2.3"
    }
}

plugins {
    id "groovy"
    id "org.grails.plugins.views-json" version "3.2.3"
    id "war"
    id "idea"
    id "application"
    id "eclipse"
}

// Not Published to Gradle Plugin Portal
apply plugin: "org.grails.grails-web"

group = "connectro.rest"

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}

configurations {
    all {
    }
}

dependencies {
    profile "org.grails.profiles:rest-api"
    implementation "org.grails:grails-core"
    implementation "org.grails:grails-logging"
    implementation "org.grails:grails-plugin-databinding"
    implementation "org.grails:grails-plugin-i18n"
    implementation "org.grails:grails-plugin-interceptors"
    implementation "org.grails:grails-plugin-rest"
    implementation "org.grails:grails-plugin-services"
    implementation "org.grails:grails-plugin-url-mappings"
    implementation "org.grails:grails-web-boot"
    implementation "org.grails.plugins:hibernate5"
    implementation "org.grails.plugins:views-json"
    implementation "org.grails.plugins:views-json-templates"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.springframework.boot:spring-boot-starter"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.springframework.boot:spring-boot-starter-validation"
    implementation("com.mysql:mysql-connector-j:9.3.0")
    compileOnly "io.micronaut:micronaut-inject-groovy"
    console "org.grails:grails-console"
    runtimeOnly "com.h2database:h2"
    runtimeOnly "org.apache.tomcat:tomcat-jdbc"
    testImplementation "io.micronaut:micronaut-inject-groovy"
    testImplementation "org.grails:grails-gorm-testing-support"
    testImplementation "org.grails:views-json-testing-support"
    testImplementation "org.spockframework:spock-core"
    compileOnly("org.projectlombok:lombok:1.18.38")
    annotationProcessor("org.projectlombok:lombok:1.18.38")

    testCompileOnly("org.projectlombok:lombok:1.18.38")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.38")

    implementation 'co.elastic.clients:elasticsearch-java:8.18.1'
    implementation 'org.elasticsearch.client:elasticsearch-rest-client:8.18.1'
    implementation 'org.apache.httpcomponents.client5:httpclient5:5.2'
    implementation 'jakarta.json:jakarta.json-api:2.0.1'
    implementation 'org.glassfish:jakarta.json:2.0.1'

    // SpringDoc OpenAPI (Swagger) - Version 1.8.0 supports Java 11
    implementation 'org.springdoc:springdoc-openapi-ui:1.8.0'



}


configurations.all {
    exclude group: 'org.elasticsearch.client', module: 'elasticsearch-rest-high-level-client'
    exclude group: 'org.elasticsearch', module: 'elasticsearch'
}

application {
    mainClass = "connectro.rest.Application"
}

java {
    sourceCompatibility = JavaVersion.toVersion("11")
    targetCompatibility = JavaVersion.toVersion("11")
}


tasks.withType(Test) {
    useJUnitPlatform()
}
