info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

grails:
  cors:
    enabled: true
  spring:
    bean-packages:
      - configurations
      - service
  mime:
    types:
      json:
      - application/json
      - text/json
  codegen:
    defaultPackage: connectro.rest
  profile: rest-api

logging:
  level:
    connectro.rest: INFO
    org.grails: INFO
    org.springframework: INFO
    service: DEBUG

elasticsearch:
  host: localhost
  port: 9200
  scheme: http
  apiKey: ${ELASTICSEARCH_API_KEY:}
  index: connectro
  requestTimeout: 30s

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: connectro.rest
